---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Terraform and Ansible Automation Platform 2.5"
      solveButton: false
    - name: module-02
      label: "Create a Terraform-enabled Execution Environment"
      solveButton: false
    - name: module-03
      label: "OPTIONAL - Terraform Basics"
      solveButton: false
    - name: module-04
      label: "OPTIONAL - Terraform and the Certified Collection for Terraform"
      solveButton: false

tabs:
  - name: aap
    url: https://control-${guid}.${domain}/
  - name: vscode
    url: https://code-server-${guid}.${domain}/
    external: false
  - name: ">_ control"
    url: /wetty
  - name: Cloud (PoC)
    url: /cloud
